name: pytorch-reproducibility
channels:
  - pytorch
  - conda-forge
  - pyg
dependencies:
  - python=3.9
  - pip
  - pytorch>=2.0.0
  - torchvision
  - cudatoolkit
  - numpy
  - matplotlib
  - networkx
  - pip:
    - torch-geometric
    - torch-scatter
    - torch-sparse 